# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16IKo1mFhvRJLB-VZJhztJB-Y3AKodtUI
"""

import math

# Define the points in a list (example points)
points = [(1, 2), (4, 6), (5, 8), (3, 1)]

# Function to calculate the Euclidean distance between two points
def euclideanDistance(point1, point2):
    return math.sqrt((point2[0] - point1[0]) ** 2 + (point2[1] - point1[1]) ** 2)

# List to store distances between all point pairs
distances = []

# Calculate distances between all point pairs and store them
for i in range(len(points)):
    for j in range(i + 1, len(points)):
        dist = euclideanDistance(points[i], points[j])
        distances.append(dist)

# Find the minimum distance
min_distance = min(distances)

# Print the results
print("Distances between points:", distances)
print("Minimum distance:", min_distance)
